# Generated by Django 5.0.2 on 2026-05-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='torrent_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
