services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    image: nginx
    restart: always
    networks:
      - hypertube_network
    ports:
      - "8082:80"
      - "8443:443"
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hypertube_network
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    networks:
      - hypertube_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: build/Dockerfile
    image: backend
    container_name: backend
    command: sh /app/start.sh
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    networks:
      - hypertube_network
    env_file:
      - .env
    environment:
      DEBUG: ${DEBUG}
      DB_HOST: db
      REDIS_HOST: redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend
    command: npm run dev -- -H 0.0.0.0 -p 3000
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    networks:
      - hypertube_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5050:80"
    networks:
      - hypertube_network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
  node_modules:

networks:
  hypertube_network:
    driver: bridge